const EXPIRES_TIME = 24 * 60 * 60 * 1000;
const ALERT = 'ALERT';
const REFETCH_CHATS = 'REFETCH_CHATS';
const NEW_ATTACHMENT = 'NEW_ATTACHMENT';
const NEW_MESSAGE_ALERT = 'NEW_MESSAGE';

export {
  EXPIRES_TIME,
  ALERT,
  REFETCH_CHATS,
  NEW_ATTACHMENT,
  NEW_MESSAGE_ALERT,
};
